#!/bin/bash

# Take dotfile branch as an option and then install that.

# Stow

# Global git config (Modify ~/.gitconfig instead)

# set bash as default shell
# chsh --shell /bin/bash

# Adds .scripts to the path, if it doesn't exist appends


# custom .bashrc call to end of bashrc if it doesn't exist
# merge my add-tobashrc script into system .bashrc
touch ~/.temp
git merge-file --union ~/.bashrc ~/.temp ~/.scripts/.add-to-bashrc
rm ~/.temp

# Should we generate key here? (Probably better)
# Add public Key to GH - Should read user name from config
ghak sierra-alpha ~/.ssh/id_rsa.pub

# Setsup git watch to associated folders
cwd1=$(echo cwd)
mkdir -p ~/src
cd ~/src
git clone https://github.com/gitwatch/gitwatch.git
cd gitwatch

# Nees to be root
install -b gitwatch.sh /usr/local/bin/gitwatch
mkdir -p "$HOME/.config/systemd/user" && cp gitwatch@.service $HOME/.config/systemd/user

cd "$cwd1"

gitwatch $(tail -n +2 ~/.kaianga/repos-to-watch) &


systemctl --user --now enable \
          gitwatch@$(systemd-escape "'-r url/to/repository' /path/to/folder").service

