# nicer pane splits
bind / split-window -h
bind - split-window -v

# reload config easy
bind r source-file ~/.tmux.conf

# mouse mode
set -g mouse on

# vi mode copy
set -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel

# set pane title bars
set -g pane-border-format "#{pane_index} #{pane_current_path} #{pane_current_command}"
set -g pane-border-status bottom

# set history-limit
set-option -g history-limit 50000

# Platform specific items

# Linux
if-shell -b '[ "$(uname -s)" = Linux ]' {
  # Copy to system clipboard also
  set -s copy-command 'xsel -i -b'

  # default shell fish
  set -g default-command "/bin/fish"
  set -g default-shell "/bin/fish"
}

# MacOS
if-shell -b '[ "$(uname -s)" = Darwin ]' {
  # Copy to system clipboard also (untested)
  set -s copy-command 'pbcopy'

  # default shell fish
  set -g default-command "/usr/local/bin/fish"
  set -g default-shell "/usr/local/bin/fish"
}


